### ISSUE TITLE
Turbo Clearcache not available?

### ISSUE THREAD

**Issue by masonjo** [tonysm/turbo-laravel#11]
I am trying to clear the cache.  I use Turbo.clearCache() in a script.  I found this on https://turbo.hotwire.dev/reference/drive.
It however does not seem to be working.  In the browser console I try the command and I get "Turbo is not defined"

My app.js has:
import {
    start as startTurbo
} from '@hotwired/turbo';

I have tried a few ways to see if I could get Turbo to be defined.

**Comment by WalterWoshid** [comment]
Remove the mentioned part in your app.js and insert this
```
window.Turbo = require('@hotwired/turbo');
Turbo.start();
```

**Comment by tonysm** [comment]
You can change the import in your `app.js` file as @WalterWoshid suggested:

```js
import * as Turbo from '@hotwired/turbo';
```

**Comment by tonysm** [comment]
I've updated the default scaffolding to the new import: https://github.com/tonysm/turbo-laravel/commit/e85955fae40192f604486cb582698fefd3b314c2

Feel free to re-open this issue if think it's not solved.
