### ISSUE TITLE
[Feature] Add ability to suppress turbo stream broadcasting

### ISSUE THREAD

**Issue by tonysm** [tonysm/turbo-laravel#12]

**Comment by cjaoude** [comment]
Sry, bit of a tangent...seems this package is more of a convenience? I tried using Turbo directly and seems to work fine. Could you clarify use case for this package or is it more just helpers. Also, seems to have not been updated in a while, wondering if it's something I should use for production. Tnx. Appreciate your efforts.

**Comment by tonysm** [comment]
I think this shouldn't be handled in core (at least I don't see a compelling reason for it). If anyone wants to do that on their own app, they can implement supression for their own app, something like this should do:

```php
trait SupressesBroadcast
{
  protected static bool $suppressedBroadcast = false;

  public static function bootSupressesBroadcast()
  {
    static::$suppressedBroadcast = false;
  }

  public static function withoutBroadcasting(callable $callback)
  {
    static::$suppressedBroadcast = true;

    return tap($callback(), fn () => static::$suppressedBroadcast = false);
  }
}

class Post extends Model
{
  use SupressedBroadcast;

  public static function booted()
  {
    static::creating(function (Post $post) {
      if (static::$suppressedBroadcast) {
        return;
      }

      $post->broadcastAppend();
    });
  } 
}
```

Which you can use like so:

```php
Post::withoutBroadcasting(function () {
  Post::create(...);
});
```

Something like this. Not sure if this code works, it's just pseudo-code. But you can picture the idea.
