### ISSUE TITLE
Feedback about Bootcamp

### ISSUE THREAD

**Issue by kresnasatya** [tonysm/turbo-laravel#131]
Hi @tonysm, thanks for creating the Turbo Laravel Bootcamp. I have finished the bootcamp. Currently my feedback is in section [**"Extra Credit: Fixing The Missing Dropdowns"**](https://turbo-laravel.com/guides/broadcasting#content-extra-credit-fixing-the-missing-dropdowns). I was confused about which dropdowns and I need to figure out. Is that user profile dropdown (top right corner) or edit and delete chirp dropdown? That's what I think at that time. Then, after I follow the tutorial I realized that the dropdown is edit and delete chirp dropdown. I think you can add a gif or image with "a pointer" to tell anyone that what you want to show is dropdown of edit and chirp. Anyway, overall the bootcamp is great! I would like to try Turbo Laravel in another use case. Thank you.

<img width="1440" alt="Screenshot 2023-11-25 at 14 15 09" src="https://github.com/hotwired-laravel/turbo-laravel/assets/11099186/e103a4b1-0920-4160-9fb2-05763d48f9f4">

**Comment by tonysm** [comment]
Thanks for reporting! Yeah, I meant the dropdown in the `chirps._chirp` partial (the one we're broadcasting to other users). I'll try to make it more clear on the revised version of the Bootcamp.

**Comment by tonysm** [comment]
@kresnasatya btw, I've deployed the [new bootcamp](https://turbo-laravel.com/guides/introduction) last night. It's shorter now as it features the [Turbo Breeze](https://github.com/hotwired-laravel/turbo-breeze) starter kit.

**Comment by kresnasatya** [comment]
Cool! I will try and give a feedback to you, Tony.
