### ISSUE TITLE
Stream responses with empty content fails unexpectedly

### ISSUE THREAD

**Issue by AEM5299** [tonysm/turbo-laravel#147]
Turbo stream responses with empty content seem to throw a MissingPartial exception.

```php
response()->update('id-xyz', '')
```

I would expect the above to clear the content of `id-xyz`. However, currently this fails and throws an exception ([here](https://github.com/hotwired-laravel/turbo-laravel/blob/fa6b03b9a3cc8b1c9e6fc65820e5487d0a1beb60/src/Http/PendingTurboStreamResponse.php#L330C1-L331C1))

I can submit a PR if I get confirmation this is not intended behaviour.

**Comment by tonysm** [comment]
Yeah, it's not intended behavior. @AEM5299 let me know if you want to tackle this, otherwise I'll do it when I have some time later this week.

**Comment by AEM5299** [comment]
Thanks for confirming. PR opened here #148.
