### ISSUE TITLE
[RFC] - Turbo Stream Broadcasting API

### ISSUE THREAD

**Issue by tonysm** [tonysm/turbo-laravel#15]
The implementation of broadcasting Turbo Streams right now differs a bit from the [turbo-rails](https://github.com/hotwired/turbo-rails) gem. I find their implementation a bit simpler, so I'd like some feedback on this one before I start changing things.

There are a couple of ways we can implement broadcasting, here's a gist.

### Broadcast With Events

We may dispatch either the `TurboStreamModelCreated`, `TurboStreamModelUpdated`, or `TurboStreamModelDeleted` events. For each event, we may specify the Turbo Stream action. Here's a couple of ways we can implement it:

#### 1. Hooking in Model Events

```php
<?php

use Tonysm\TurboLaravel\Events\TurboStreamModelCreated;

class Message extends Model
{
  protected $dispatchesEvents = [
    'created' => TurboStreamModelCreated::class,
  ];
}
```

This way we cannot specify the Turbo Stream action that the event supports, so it will use whatever is the default action. This one is simple to demo, but in reality, I wouldn't use this approach myself, I think.

#### 2. Manually Triggering Events

It's also possible to dispatch the model events manually at any point in time.

```php
event(new TurboStreamModelCreated($message)); // Using the default Turbo Stream action

event(new TurboStreamModelCreated($message, 'prepend')); // Specifying another action
```

This way you may also hook into model events, like so:

```php
class Message extends Model
{
  protected static function booted()
  {
    static::created(function (Message $message) {
      event(new TurboStreamModelCreated($message, 'prepend'));
    });
  }
}
```

Or maybe, I don't know, inside a background job:

```php
class SomeBackgroundJob implements ShouldQueue
{
  public function handle()
  {
    $message = Message::create([ /** ... */ ]);

    event(new TurboStreamModelCreated($message, 'prepend'));
  }
}
```

This approach gives you full control over the model and the action.

### Broadcast with the Broadcasts Trait

Another approach is using the `Broadcasts` trait, which may look like this:

```php
<?php

use Tonysm\TurboLaravel\Models\Broadcasts;

class Message extends Model
{
  use Broadcasts;
}
```

There is all there is to it. The package will now broadcast any model changes that happen with objects of this class (hooking into the created, updated, or deleted model events).

### Resolving the Partial

By default, the package will generate the Turbo Stream tag for your broadcasts. It guesses the partial name based on the model name, so for our `Message` model, it would infer the resource name as the plural of the model basename and the partial will be a singular version of the model basename prefixed with an underscore. Our example would look for a partial at `resources/views/messages/_message.blade.php`.

If the model was created, it will generate a Turbo Stream such as:

```html
<turbo-stream target="messages" action="append">
  <template><!-- partial --></template>
</turbo-stream>
```

The `target` attribute uses the resource name, the action will default to `append` when the model was created. Both the resource name and the action can be overridden in the model, such as:

```php
class Message extends Model
{
  use Broadcasts;

  public $turboStreamCreatedAction = 'prepend';
  public $turboStreamResourceName = 'messages';
}
```

### Responding Form Submissions With Turbo Streams

Here's how we can return a Turbo Stream response from a controller after form submission:

```php
class MessagesController extends Controller
{
  public function store()
  {
    $message = Message::create(request()->validate([/** ... */]));

    if (request()->wantsTurboStream()) {
      return response()->turboStream($message);
    }

    return redirect()->route('messages.index');
  }
}
```

This will make use of the same conventions as broadcasting. In fact, as broadcasting doesn't seem to be that common (from what I can see), this will likely be the primary way of consuming the package.

### Custom Turbo Stream View

As I said earlier, by default, the package will generate the Turbo Stream view for your model changes both when returning from HTTP or when generating the Turbo Stream changeset in the background for your broadcasts. You only *need* to have a partial file for your model.

However, sometimes we want to have more control over the Turbo Stream change sent to the browser. For that reason, I added a conventional layer on the "guessing the partial" flow. If you have a view in a special `turbo/` folder inside your model's resource views folder that follows the Laravel model events convention, the package won't generate a view for you, but instead will use that custom view, where you can place your Turbo Stream tags and have full control over the stream changes sent to the browser.

This happens both for broadcasting and returning Turbo Streams from form submissions. Here's the view pattern:

```
resources/views/{resource}/turbo/{created|updated|deleted}_stream.blade.php
```

Here's what one of these custom views look like:

```blade
<turbo-stream target="tweets" action="prepend">
    <template>
        @include ('tweets._tweet', ['tweet' => $tweet])
    </template>
</turbo-stream>

<turbo-stream target="empty_tweets" action="remove"></turbo-stream>

@if ($tweet->wasRecentlyCreated)
    <turbo-stream target="create_tweet" action="update">
        <template>
            @include ('tweets._form', ['tweet' => new \App\Models\Tweet()])
        </template>
    </turbo-stream>
@endif
```

One thing that you notice here is the check for `$tweet->wasRecentlyCreated`. That's exactly because this view is used both for the HTTP response and for broadcasting new Tweets to users, and we don't want to refresh another user's New Tweet box whenever someone else posts a New Tweet.

This is the "could be improved" part of the package. It could be resolved by having the HTTP Turbo Stream view separately from the broadcasting one. That seems to be how the turbo-rails gem does it, the do:

```ruby
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.turbo_stream
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
end
```

See the `format.turbo_stream` empty? That's because Rails will do some "magic" content negotiation to figure out the correct view to render (convention over configuration), the `@message = ` there assigns the variable to the controller, and any variable assigned to the controller will be available on the view. So, since the Turbo Stream request is annotated with a Turbo Stream Content-Type, Rails will know to look for a: `app/views/messages/create.turbo_stream.erb` view (it finds the best view using the `controller/action` convention) for the response content-type, which in this case is `.turbo_stream.erb`.

Anyways, the point is that this part is much more "lighter" than having everything in a single view.

### What It Could Be

The closest to that we could get with the current implementation would be to not use the custom turbo view for HTTP, creating another view entirely, maybe a `resources/views/message/store_turbo_stream.blade.php` and return that from the controller, like so:

```php
class MessagesController extends Controller
{
  public function store()
  {
    $message = Message::create(request()->validate([/** ... */]));

    if (request()->wantsTurboStream()) {
      return response()->turboStreamView('messages.store_turbo_stream', ['message' => $message]);
    }

    return redirect()->route('messages.index');
  }
}
```

This already is possible right now. And the broadcasting we could allow passing the template to the model events, something like:

```php
class Message extends Model
{
  protected static function booted()
  {
    static::created(function (Message $message) {
      event(new TurboStreamModelCreated(
        model: $message,
        action: 'prepend',
        partial: 'messages.turbo.created_stream',
        data: ['something' => 'else'],
      ));
    });
  }
}
```

This part is not possible yet. But I think it wouldn't require much work to make it possible.

I wanted some feedback on this. Not sure which direction we should take. Right now, the custom turbo stream views "convention" layer doesn't feel like it brings much to the game and it kind of mixes HTTP responses and broadcasting rendering. Easy to check for that on created events because the model will have the `$model->wasRecentlyCreated` marked as true, but for the updated ones it's kinda tricky.

Say you're rendering a flash message when updating messages saying the message was successfully updated. You want that to only appear to the user making the changes. How would you go about it?

One way to achieve this would be to check if the template is being rendered in the console, I guess. Since broadcasts will be processed in background by a queue worker that runs in the console, that could work. So that template would be something like:

```blade
<turbo-stream target="@domid($message)" action="replace">
    <template>
        @include ('messages._message', ['message' => $message])
    </template>
</turbo-stream>

@if ($message->wasChanged())
    <turbo-stream target="notices" action="append">
        <template>
            @include ('flash.message', ['message' => __('Message was suggessfully updated!')])
        </template>
    </turbo-stream>
@endif
```

I wonder if anyone has any opinion on this or if you can think of a better port for the `turbo-rails` gem that you wish it was like.

The way I see it, there is no harm in making re-using the same view for rendering steps (HTTP/broadcasting), but if there is a better version, I'd like to see what it is like.

**Comment by tortuetorche** [comment]
Hi @tonysm,

I'm not going to comment all your thoughts on the Turbo Stream Broadcasting API, you have a better understanding of this than me.
I just want to say, to be in parity with the `turbo-rails` gem is the way, of course with some PHP/Laravel constraints or conventions in mind 👍

Maybe I'm a bit off topic, but I like this syntax in the `turbo-rails` gem, it's very readable:
```ruby
def destroy
  @user.destroy!

  respond_to do |format|
    format.turbo_stream { render turbo_stream: turbo_stream.remove(@user) }
    format.html         { redirect_to users_url, notice: "User removed" }
  end
end
```
Reference: https://github.com/hotwired/turbo-rails/blob/v0.5.9/app/controllers/turbo/streams/turbo_streams_tag_builder.rb#L5

The `turbo_stream.remove(@user)` is easy to understand, here all the methods available for the `turbo_stream` instance: https://github.com/hotwired/turbo-rails/blob/v0.5.9/app/models/turbo/streams/tag_builder.rb

I don't know if we can have this kind of API in `turbo-laravel` (only inside a controller I mean), maybe with some DSL of this class: https://github.com/tonysm/turbo-laravel/blob/0.3.2/src/TurboStreamResponseMacro.php#L34 🤔

Have a good day,
Tortue Torche

**Comment by tonysm** [comment]
Hey. I've been thinking of some changes in the API.

- Using the trait will not automatically hook into the model's events to broadcast the changes. Users would have to either hook it themselves or use add a `$broadcastsTo` property to the models which should instruct the trait to hook into the models events and broadcast the changes. See examples below;
- Change the broadcasting method name. They were written for internal usage, so they had a `hotwire*` prefix on them, but I think we should make them part of the public API of the model. See examples below for what it may look like;
- Streamline broadcasting events and jobs into a single pair;

Using the `Broadcasts` trait is optional as of right now. I think we should make that not optional. If you want to make use of Turbo Streams, you would have to use the Broadcasts trait.

Currently, hooking the trait to a model automatically binds into the model events to send the broadcasts. That will change. The trait will not auto-wire into the model events. Instead, the model would have to either declare their own broadcasting hooks:

```php
class Message extends Model
{
  use Broadcasts;

  public static function booted()
  {
    static::created(function (Message $message) {
      $message->broadcastAppend()
        ->target('channel_messages') // optional, default: plural of model name
        ->partial('messages._message') // optional
        ->later(); // optional
    });
  }
}
```

Here's the API of the available methods and some of the arguments I can think of:

```php
interface Broadcastable
{
  public function broadcastAppend(): PendingBroadcast;
  public function broadcastPrepend(): PendingBroadcast;
  public function broadcastReplace(): PendingBroadcast;
  public function broadcastUpdate(): PendingBroadcast;
  public function broadcastRemove(): PendingBroadcast;
}
```

This new `PendingBroadcast` class will use the `__destruct` trick that is common in Laravel. It would look something like this:

```php
class PendingBroadcast
{
  private array $streamables;
  private ?string $target = null;
  private ?string $partial = null;
  private bool $later = false;
  private bool $toOthers = false;

  public function __construct(Broadcastable $to)
  {
    $this->streamables = Arr::wrap($to);
  }

  public function to(Broadcastable|array $to): self
  {
    $this->streamables = Arr::wrap($to);
    return $this;
  }

  public function target(string $target): self
  {
    $this->target = $target;
    return $this;
  }

  public function partial(string $partial): self
  {
    $this->partial = $partial;
    return $this;
  }

  public function later(): self
  {
    $this->later = true;
    return $this;
  }

  public function toOthers(): self
  {
    $this->toOthers = true;
    return $this;
  }

  public function __destruct()
  {
    $broadcastable = Arr::first($streambles)->hotwireBroadcastUsing();
    $socket = $this->toOthers || Turbo::shouldBroadcastToOthers() ? Broadcast::socket() : null;

    foreach ($this->streamables as $streamable)
    {
      $broadcastable->exceptForSocket($socket)->broadcast(
        $streamable,
        $this->target,
        $this->partial,
        $this->later,
      );
    }
  }
}
```

This is just an example, I haven't really tried implementing this yet, so there might be some changes, but this is the idea. The Broadcastable is just for the sake of demonstration, those methods would be added to the trait.

Here's an example of a controller that does NOT use the hooks:

```php
class ChannelMessagesController
{
  public function store(Channel $channel)
  {
    $message = $channel->addMessage(request()->user()->messages()->make(request()->validate([
      'content' => 'required|min:1|max:500',
    ])));

    $message->broadcastAppend()->toOthers();

    if (request()->wantsTurboStream()) {
      return response()->turboStream(
        $message,
        target: 'channel_messages', // optional, default to plural name of the model
        partial: 'messages._message', // optiona, default to same
        data: [/** Control the data */],
      );
    }
    
    return redirect()->route('channels.show', $channel);
  }
}
```

**Comment by tonysm** [comment]
The new broadcasting API was merged. I'm closing this one. I'll create another issue to accommodate the HTTP response generation. I've got some ideas about it.
