### ISSUE TITLE
[RFC] Simplified Turbo Stream Generation for HTTP Responses

### ISSUE THREAD

**Issue by tonysm** [tonysm/turbo-laravel#18]
_This was brought up at the [Broadcasting API RFC](https://github.com/tonysm/turbo-laravel/issues/15#issuecomment-800402470)._

Currently, when we want to return Turbo Streams for HTTP requests, we have the following syntax:

```php
return response()->turboStream($comment);
```

If the model was recently created, it will render an `append` action to a `comments` target, rendering the comment partial located at `comments._comment` passing the comment to it.

If the model was deleted, it will render a remove Turbo Stream tag using the model DOM ID.

Otherwise, the model was likely updated, so it renders a _replace_ Turbo Stream action using the DOM ID as a target, rendering the comment partial located at `comments._comment` passing the comment model to it.

Well, at least that's the _default_ way. If, however, you implement Custom Turbo Stream Views, it uses that instead of generating a Turbo Stream tag for you. The custom ones are:

| Model Event | Custom Turbo Stream View |
|---|---|
| `created` | `comments.turbo.created_stream.blade.php` |
| `deleted` | `comments.turbo.deleted_stream.blade.php` |
| `updated` | `comments.turbo.updated_stream.blade.php` |

If these exist, we'll render those.

These are only used when generating Turbo Stream responses for the Model. **These are not used when automatically generating Turbo Streams for Broadcasts anymore!**

I'm not sure if the `{resource}.turbo.{event}_stream.blade.php` convention was a good idea. I like it, but we can simplify the package quite a lot if we simply remove it and come up with another way to generate inline Turbo Stream HTTP responses + the existing `response()->turboStreamView('comments.turbo.created_stream', data: [])` syntax if we want more fine-grained control over the HTTP Responses.

### Proposal

First, I'd like to suggest:

1. **Keep** the existing syntax for generating a custom turbo stream HTTP response pointing to a view, like:

```php
return response()->turboStreamView('comments.created_stream', [
  'comment' => $comment,
]);
```

These views you would have full control over the Turbo Stream tags rendered. It could be something like:

```blade
<turbo-stream action="append" target="comments">
  <template>
    @include('comments._comment', ['comment' => $comment])
  </template>
</turbo-stream>

<turbo-stream action="update" target="@domid($comment->post, 'create_comment')">
  <template>
    @include('comments._form', ['comment' => new Comment()])
  </template>
</turbo-stream>
```

2. **Remove** the convention of loading custom views when rendering HTTP responses. This would mean that this code:

```php
return response()->turboStream($comment);
```

Would always generate the HTTP response for the model. The custom views would never be _automatically_ used. You could still use the views by referencing them in the `response()->turboStreamView()` API, though.

3. **Add** named parameters to the `response()->turboStream()` helper to allow overriding everything **and make the model optional**. This would essentially make this:

```php
return response()->turboStream(
  $comment,
  action: 'prepend',
);
```

Possible. But it would also open up the API so we could do something like:

```php
return response()->turboStream(
   action: 'remove',
   target: dom_id($post, 'create_comment')
);
```

And things like this:

```php
return response()->turboStream(
  $comment,
  action: 'append',
  target: dom_id($post, 'comments_cards'),
);
```

This would be the full API:

```php
return response()->turboStream(
  action: 'prepend',
  target: dom_id($post, 'comments_cards'),
  partial: 'comments._comment_card',
  partialData: ['comment' => $comment, 'post' => $post],
);
```

Passing the model would essentially be used to figure out the default _action_, _target_, _partial_, and _partial data_. All of these could be overwritten by the developer, which would not make sense to pass the model, therefore we could make it optional.

---

Thoughts?

**Comment by tonysm** [comment]
hey @tortuetorche what do you think?

**Comment by tonysm** [comment]
Uhm, actually, I think I would prefer to return a `PendingTurboResponse` instance instead... this way, instead of overriding the defaults as named parameters, we could use the same pending object pattern as the Broadcasts:

```php
return response()->turboStream($comment)
  ->action('prepend')
  ->target(dom_id($post, 'comments_cards');
```

And the model would be optional as well, so:

```php
return response()->turboStream()
  ->action('prepend')
  ->target(dom_id($post, 'comments_cards'))
  ->partial('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
   );
```

And we could throw an exception in case one of these is missing in required ways, like:

```php
if (! $this->partial && $this->action !== "remove") {
  throw TurboStreamResponseFailed::missingPartial();
}
```

Which would make it nice to test, I think.

**Comment by tortuetorche** [comment]
Hi @tonysm,

I think this is great!

Just few notes, based on this sample:
```php
return response()->turboStream()
  ->action('prepend')
  ->target(dom_id($post, 'comments_cards'))
  ->partial('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
  ]);
```

You could also add some `action` and `target` _shortcut_ methods, like the [`turbo-rails` gem](https://github.com/hotwired/turbo-rails/blob/v0.5.9/app/models/turbo/streams/tag_builder.rb#L39):
```php
return response()->turboStream()
  ->remove(dom_id($post, 'comments_cards'));

return response()->turboStream()
  ->prepend(dom_id($post, 'comments_cards'))
  ->partial('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
  ]);

return response()->turboStream()
  ->replace(dom_id($post, 'comments_cards'))
  ->partial('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
  ]);

//...
```

Maybe the `partial()` method should be renamed `view()` because the `partial` term is easily understandable for a Rails developer, but maybe not for a Laravel developer 🤔

And this method should allow both a view name with an array of parameters or a view instance, like the `turboStreamView()` method:
```php
return response()->turboStream()
  ->action('prepend')
  ->view('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
  ]);

// or
return response()->turboStream()
  ->action('prepend')
  ->view(view('comments._comment_card', [
     'comment' => $comment,
     'post' => $post,
  ]));
```

> And we could throw an exception in case one of these is missing in required ways, like:
```php
if (! $this->partial && $this->action !== "remove") {
  throw TurboStreamResponseFailed::missingPartial();
}
```

Look like the `allow_inferred_rendering` option in the [`turbo-rails` gem](https://github.com/hotwired/turbo-rails/blob/v0.5.9/app/models/turbo/streams/tag_builder.rb#L98)  😉

Many thanks for this work and have a good day 👍
Tortue Torche

**Comment by tonysm** [comment]
This is done and merged. New documentation is on the readme.
