### ISSUE TITLE
Use turbo-frame with table

### ISSUE THREAD

**Issue by vanthao03596** [tonysm/turbo-laravel#20]
Is there any way to use turbo with tr tag? 
i can't make it work.

**Comment by tonysm** [comment]
Nope. Tables have a very strict structure. There are resources [here](https://discuss.hotwire.dev/t/how-to-wrap-a-table-row-with-a-turbo-frame/1717/11), but I would say avoid tables if you can. You can append, replace, prepend TRs to a TBODY with Turbo Streams (as long as the TBODY has an ID), and you can wrap the content inside a TD in a turbo frame and replace that, but yeah, it's tricky.
