### ISSUE TITLE
no-cache problem when using livewire.

### ISSUE THREAD

**Issue by jskorlol** [tonysm/turbo-laravel#35]
```html
<meta name="turbo-cache-control" content="no-cache">
```
Because I'm having issues with caching menus, etc. I gave you that option.
But, if I give this option and go to another page
```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$wire')
```
An error occurs.

I used this option in turbolinks, is it not possible to use it in turbo?

**Comment by jskorlol** [comment]
Problems arise when using no-cache,
To solve the content caching, using ``<meta name="turbo-cache-control" content="no-preview">`` seems to have solved it.

**Comment by tonysm** [comment]
I don't see how that could break the package. It seems you're using Livewire. If so, make sure you're on the latest version. Also, make sure you're using the [Livewire/Turbo Bridge](https://github.com/livewire/turbolinks). And if you're using Alpine, also make sure you're using the latest version, 'cause there's a fix for Turbo there.

I'm closing the issue for now, feel free to reopen it. But, please, provide more info on what stack you're using, and maybe try to create a sample application reproducing the error and publish it to GitHub so I can take a look.

Cheers,
