### ISSUE TITLE
Making Turbo load content or page in a div

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#46]
Hello is there away to make turbo load content into a particular div instead of navigating from one page to another,

after installing this package successfully it work well with livewire but i want the to be loading the content into a particular div when navigating from one page to another

**Comment by davidgut** [comment]
If what you want is the content of a specific div to be replaced instead of the whole page, you can use data-turbo-frame="id of the target div" and data-turbo-action="advance" to promote navigation to visits so the url changes. See https://turbo.hotwired.dev/reference/frames
