### ISSUE TITLE
Turbo frame slow

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#47]
Turbo frame not loading faster when navigating from one page to another page

**Comment by tonysm** [comment]
Not sure what you mean here. Can you elaborate?

**Comment by odion-cloud** [comment]
when i reload the page the Turbo frame load fast, but when i  navigate from one page to another page the turbo frame  take some few time to load

**Comment by tonysm** [comment]
Sorry, there's nothing in a Turbo Frame that "slows it down" depending on the type of visit (first full page fresh vs. turbo visit). What may be happening there is that the lazy-loading Turbo Frame will only be trigger after the full page render. Which means there will be a noticeable delay there.

You can solve this in two ways:

**Add a placeholder to the first turbo frame content**, which would look like this:

```blade
<x-turbo-frame id="my_frame" :src="route('my-route')" loading="lazy">
  <p>I'm a placeholder. I'll be replaced when the Turbo Frame content loads.</p>
</x-turbo-frame>
```

Or you can also **cache the Turbo Frame content and serve the cache on the first render**. Trickier to implement here, but you can take a look at this implementation [here on Laracasts](https://laracasts.com/series/javascript-techniques-for-server-side-developers/episodes/2). The idea is the same.
