### ISSUE TITLE
Turbo Issue with Livewire

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#48]
when navigating from one page to another page with Turbo on livewire full page component, the page load well but prevent livewire function from working, E.g the wire:click="" stop working and mount function as well

**Comment by tonysm** [comment]
Are you using the [Livewire Turbolinks](https://github.com/livewire/turbolinks) bridge?

**Comment by odion-cloud** [comment]
thank you it work well now with Livewire Turbolinks bridge
