### ISSUE TITLE
passing varieble to turbo frame

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#49]
this is my turbo frame to fetch content with varieble
```
<x-turbo-frame id="RightdDefualtbar" :src="route('user.homecomponent')" loading="lazy">
loader here
</x-turbo-frame>
```

but it return under fine varieble is there a way to pass variable to the turbo frame exampl like this 

`<x-turbo-frame id="RightdDefualtbar" :src="route('user.homecomponent',{variable here})" loading="lazy">`

**Comment by tonysm** [comment]
You can use variables from the outer scope of the Turbo Frame inside the view (variables declared outside the Turbo Frame itself):

```blade
<x-turbo-frame id="my_frame">
  <h1>{{ $post->title }}</h1>
</x-turbo-frame>
```

The `$post` variable was declared somewhere else, probably in a controller.

If you want to pass URL params to the Turbo Stream `src`, you need to encode that in the query string, like so:

```blade
<x-turbo-frame id="my_frame" :src="route('my-route', ['someparam' => 'lorem'])" >
</x-turbo-frame>
```

In the controller where you handle the `GET /my-route?someparam=lorem` route, you will have access to the `someparam` query string, so you can use it like any other request params: `request('someparam')`.
