### ISSUE TITLE
How to handle soft-deletes

### ISSUE THREAD

**Issue by tonysm** [tonysm/turbo-laravel#5]
I'm not sure how to handle soft-deletes yet, so would love some ideas on this.

**Comment by tonysm** [comment]
I think for soft-deletes it should handle as a regular delete. The item would be removed from lists on the page. But I'm not sure what we should do about the instances where the resource is on the screen (like showing a post and the post was deleted). Should we replace the post frame with a new render of the post partial? Or is that too specific for the library and should be handled in the app instead?

**Comment by tonysm** [comment]
I think this concern is also for regular deletes. Should we replace the element with a new render of the frame for regular deletes and tell any list to remove it from there? I think this is a nice solution. 🤔

**Comment by georgeboot** [comment]
Yeah I would say there isn't too much difference between the two. It all depends on the use case. Sometimes, you want to 'grey-out' an item when it gets deleted, sometimes you want to completely remove it from the list.

Thus, one should have the option what to do on a (soft) delete: update or actually remove the item.

**Comment by tonysm** [comment]
yeah, I was just thinking about what the default option should be. After sleeping on it a bit, I think we should handle it as a regular delete (remove from lists). If we need more control, we can override the "deleted_stream.blade.php" template, I guess.

**Comment by tonysm** [comment]
We'll handle soft-deletes as regular deletes. For applications that need more fidelity on soft-deletes, it's recommended to implement your customization on the `turbo/deleted_stream.blade.php` template.

**Comment by tortuetorche** [comment]
Hi @tonysm,

Sorry to comment on this closed issue, but I don't think soft-deletes are handle as regular deletes right now.

According to this line: https://github.com/tonysm/turbo-laravel/blob/0.3.2/src/TurboStreamResponseMacro.php#L19

You check if the model exists, but a soft deleted model response to `true` on this `exists` attribute.

Maybe, you can do something like this?
```php

        if (! $model->exists ||
            (method_exists($model, 'trashed') && $model->trashed())
        ) {
            return $this->renderModelDeletedStream($model);
        }
```

Have a good day,
Tortue Torche
