### ISSUE TITLE
turbo frame with laravel previous url

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#50]
when i load the first page the turbo frame load and when i navigate from one page to another the turbo frame for that page load and when i hover href=""   button with {{ url()->previous() }} for previous page it show turbo frame link , is there a way to make the previous helper not to get turbo frame as the previous link

**Comment by tonysm** [comment]
Sorry, I don't understand the problem. Can you maybe create a demo app repository where I can see the error?

I'll close this issue because it needs more details. Feel free to reopen it if you have more details on this.

**Comment by SylarRuby** [comment]
Sorry, just seen this issue. Maybe close mine and reopen this one? Mine has an example.
