### ISSUE TITLE
dropdown and side navbar dropdown

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#52]
Hello thank for your assistant this while, well i have this issue of dropdown stop working once i navigate from one page to another, the dropdown stop working ,drop down only work on first page load . 

but when i added  
`data-turbolinks-eval="false" data-turbo-eval="false"`
to all the CSS plugins and JS plugins in my app layouts the dropdowns work well when navigating , but i still don't understand while that make it work and if it best method

**Comment by tonysm** [comment]
Which dropdown are you talking about? Are you getting any errors in the console?

Here are some hints:

1. Check the Turbo documentation on why you need data-turbo-eval="false" on some scripts (you don't need these in CSS): [link](https://turbo.hotwired.dev/handbook/building#working-with-script-elements)
2. Make sure you're using the Livewire Turbolinks bridge if you're using Livewire (there's a section in the README about this, search for "Livewire"): [link](https://github.com/livewire/turbolinks)
3. Alpine may need some assistance if you're using permanent elements, make sure you have this piece of code if you're using Alpine: [link](https://github.com/tonysm/turbo-laravel/blob/main/stubs/resources/js/libs/alpine.js)

**Comment by tonysm** [comment]
Closing it for now. Feel free to reopen if you still have questions about it.
