### ISSUE TITLE
Target a child turbo-frame without having to create another blade

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#66]
Hi!

Here is an extract of my code.

```HTML
<!-- listings/_listing.blade.php -->
<x-turbo-frame :id="$listing">
    <img />
    <div>Description</div>
    <x-turbo-frame :id=["$listing", "quantity_component"]>
        <div>
            <form action="/prototype/variant/{{ $listing->variant->id }}/decrease" method="POST">
                @csrf
                <button>
                    -
                </button>
            </form>
    
            <x-turbo-frame :id="[$listing, 'quantity_in_cart']">
                <input value="{{ $listing->quantity_in_cart }}">
            </x-turbo-frame>
    
            <form action="/prototype/variant/{{ $listing->variant->id }}/increase" method="POST">
                @csrf
                <button>
                    +
                </button>
            </form>
        </div>
    </x-turbo-frame>
</x-turbo-frame>
```

```PHP
if (request()->wantsTurboStream()) {    
    // return response()->turboStream($listing) // this doesn't work, it takes the whole _listing.blade.php 
    //     ->target(dom_id($listing, 'quantity_in_cart')); // and puts it into the quantity_in_cart turbo-frame

    // this targets :id="$listing", not as efficient, causes img to reload as well
    return response()->turboStream($listing);
}
```

1. Is there a way to write the PHP to replace only the `quantity_in_cart` without having to extract its insides into another blade file?
2. Is there a convention on naming the blade if I were to extract it?
3. If extraction is a must, does it make sense to add a method `->returnOnly("quantity_in_cart_listing_xxx")`? (Yes, I'm aware of the performance hit haha)

I try to keep my blade files relatively intact so that it is still possible to get an overview when reading it. Hope I'm making sense here. 

The above is a numeric increase/decrease component, I'm planning to replace the `input` quantity with a `<a>` such that if it is clicked, the `quantity_component` will turn into a form with 1 textbox and save button. Would appreciate if you could share how to name/organize the blade files so that it remains readable.

Thank you!

**Comment by bilogic** [comment]
I made quite a bit of progress and wanted to add on to this.


Perhaps `->returnOnly[[... array of frames...]);` which in turn gets "translated" into Turbo Stream combo https://github.com/tonysm/turbo-laravel#turbo-streams-combo will make code shorter

**Comment by tonysm** [comment]
So you want to limit which pieces of the view will be returned based on the DOM element? I try to limit the package to how the turbo-rails gem work as much as I can and that's not built-in there.

One thing you could try is extracting that DOM element to another partial/view/snippet, and use the `view()` helper. Something like:

```php
return response()
  ->turboStream($listing)
  ->action(dom_id($listing, 'quantity_in_cart'))
  ->view('listings._quantity_in_cart_listing', ['any' => 'local variable']);
```

All the conventions I use are documented in the [readme](https://github.com/tonysm/turbo-laravel#conventions). I find it useful to break up a view into smaller chunks if I want to reuse them.
