### ISSUE TITLE
Turbo Stream `append(...)` requires a model

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#68]
Hi,

```HTML
<turbo-frame id="list">
...
</turbo-frame>

<turbo-frame id="action">
    <button>More</button>
</turbo-frame>
```

I'm trying to achieve infinite scrolling. Basically, when the `More` button is pressed, it gets a turbo stream combo, one to append to `list`, another to replace/update `action` with a new `More` button.

However `append()` insists on having a model. Is it a limitation on turbo? Any suggestions on what I can do for now? Thank you.

**Comment by bilogic** [comment]
Sorry, should have tried before asking. 
Replace `->append(...)` with `action("append")`.

Can I file a PR so that `->append()` will call `->action("append")`? Small quality of life improvement. :)

**Comment by tonysm** [comment]
Yeah, I've noticed the turbo-rails gem allows passing the DOM ID or a model to the shortcut methods. Something I missed on my implementation. I'll try to handle this soon, but feel free to give it a try if you want to!

**Comment by bilogic** [comment]
Ok, I will file a PR. I already managed to get my infinite scrolling to work :)

**Comment by tonysm** [comment]
As of [1.3.0](https://github.com/tonysm/turbo-laravel/releases/tag/1.3.0) you're now able to specify the DOM ID as a string in the shorthand methods, as well as passing a second optional content parameter to them, which can either be a string, an instance of a View, or a carefully handcrafted `HtmlString` instance. Docs were updated. Here's some quick examples:

```php
// Chaining the view
response()->turboStream()->update('some_dom_id')->view('my-view', ['name' => 'lorem']);

// View as content
response()->turboStream()->before('some_dom_id', view('my-view', ['name' => 'lorem']));

// String as content
response()->turboStream()->update('heading_title', $post->title);

// Carefully handcrafted HtmlString instance
response()->turboStream()->append('quote', new HtmlString(
  Blade::render('quotes', ['quote' => Inspiring::quote()]),
)); 
```
