### ISSUE TITLE
[ADD] `wantsTurboFrame` for `GET` requests

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#69]
I'm doing a search function and would like to submit the form as `GET` so that it updates the URL as well.

Since there is a `wantsTurboStream` examining the `accept` header, does it make sense to add `wantsTurboFrame` to examine for the `turbo-frame` header? This way, backend will know to send a partial instead of the full render.

**Comment by bilogic** [comment]
Please ignore above, it appears the turbo 
middleware is already handling turbo frames.

**Comment by tonysm** [comment]
You can detect if the request was made targeting a Turbo Frame by checking if there's a Turbo-Frame header in the request (Turbo adds that). Something like this:

```php
if (request()->headers->has('Turbo-Frame')) {
  // handle differently...
}
```
