### ISSUE TITLE
Example of loading spinner after submit (without javascript)

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#70]
Hi,

Would you happen to have an example of how to show a spinner after a form is submitted?
I'm working on an instant search, currently, after my new search term is submitted, the current results remain on page with no signs of activity.

I'm looking to change such that the current results are replaced with a spinner once the form is submitted and further replaced when the server responds. Would be even better if this can be achieved without javascript.

Thank you!

**Comment by tonysm** [comment]
Hey, if your search form targets the turbo frame of the search result, Turbo adds a `busy` attribute to the Turbo Frame. You could style the current results while the search is being processed by targeting that attribute, something like:

```css
turbo-frame[busy] {
  opacity: .5;
}
```

Or, if you're on the latest TailwindCSS (>=3.1) and want to use the new arbitrary variants:

```blade
<x-turbo-frame id="search-results" class="[[busy]]:animate-pulse">
</x-turbo-frame>
```
