### ISSUE TITLE
Errors When Installing v1.4.0

### ISSUE THREAD

**Issue by stevebrainng** [tonysm/turbo-laravel#76]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tonysm/turbo-laravel ^1.4 -> satisfiable by tonysm/turbo-laravel[1.4.0].
    - tonysm/turbo-laravel 1.4.0 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by tonysm** [comment]
Which version of Laravel are you using? Can you try running `composer prohibits tonysm/turbo-laravel 1.4` and dumping the output here?

**Comment by stevebrainng** [comment]
I'm using LA v8.12 

when I run 
 composer prohibits tonysm/turbo-laravel 1.4

I get this Error 


  [InvalidArgumentException]
  Could not find package "tonysm/turbo-laravel" in your project


prohibits [-r|--recursive] [-t|--tree] [--] <package> <version>

**Comment by tonysm** [comment]
Yeah, I dropped support for Laravel 8 (I don't run that anymore), but I'll try to bring it back since I did so without a major version bump. Sorry for the trouble. There should be a fix soon.

**Comment by stevebrainng** [comment]
Thanks alot, Tony, I'm looking forward to what I can contribute.

**Comment by tonysm** [comment]
@stevebrainng can you try again? I've just published v1.4.1

**Comment by stevebrainng** [comment]
Done and Installed. Thanks Tony
