### ISSUE TITLE
Uncaught TypeError: Livewire.on is not a function

### ISSUE THREAD

**Issue by dhruva81** [tonysm/turbo-laravel#79]
I am receiving following error in console.

`Uncaught TypeError: Livewire.on is not a function`

I have installed turbo-laravel package and also using livewire-turbolinks bridge.

**Comment by tonysm** [comment]
Uhm, I don't see that in my app. @dhruva81 Can you try creating a sample app where you're reproducing the issue, publish it on GitHub, and drop the link here?

**Comment by MACscr** [comment]
> 

Would you mind sharing your change here for others benefit? I am using the same package and running into the same error.
