### ISSUE TITLE
Release preparation

### ISSUE THREAD

**Issue by tonysm** [tonysm/turbo-laravel#88]
Just so I don't forget.

Release notes:
- New return types to the macros: [here](https://github.com/tonysm/turbo-laravel/pull/84) and [here](https://github.com/tonysm/turbo-laravel/pull/85)
- New `targets` behavior (needs documentation, don't forget  the new `*All()` methods) - [here](https://github.com/tonysm/turbo-laravel/pull/86) and [here](https://github.com/tonysm/turbo-laravel/pull/87)
- Stimulus options were removed (see [here](https://github.com/tonysm/turbo-laravel/pull/89))
- New `turbo_stream()` and `turbo_stream_view()` helper functions (needs documentation) - see [here](https://github.com/tonysm/turbo-laravel/pull/92)

Note: The targets change needs to be tested properly. We need to create some queued Turbo Stream broadcasts with the previous package version, let them sleep in the queue as we update the package, then try to process them with the new package version. I think it should be fine, but not sure. If this works fine, we can tag a minor version. Otherwise, we will need a major version bump.

**Comment by timvdalen** [comment]
Awesome work! One thing to note: the signature for the `Stream` component did change, so it might be safest to assume someone is using that (since it's part of the public API) and go up a major version.

**Comment by tonysm** [comment]
@timvdalen yeah but by the way components are used, it's not really a breaking change... I mean, they are only used inside Blade views, so from that point of view, the signature change is really not a breaking change 🤔

**Comment by timvdalen** [comment]
Yeah I guess it depends on if anyone has used them directly, but I would think not!

**Comment by tonysm** [comment]
For reference, I've tested out having queued jobs on the previous version of the `BroadcastAction` job stored and upgrading, one bug happened which was related to the new `$targets` property not being initialized (since the class was serialized and then unserialized from the queue without any value). Setting the nullable properties to `null` by default fixed this issue ([here](https://github.com/tonysm/turbo-laravel/commit/7abbbdd31aaa02cabebcb80022685c76eedb4500)), so I think we can move on with the release tagging a minor version.

If anyone has an issue with this, let me know.

**Comment by tonysm** [comment]
Version [1.6.0 was released](https://github.com/tonysm/turbo-laravel/releases/tag/1.6.0). 🎉🎉🎉
