### ISSUE TITLE
How can I show loading spinner with disabled submit button when a post request is send.

### ISSUE THREAD

**Issue by dhruva81** [tonysm/turbo-laravel#9]
On clicking submit button of a form, how can i disable the button or display loading spinner so that the visitor can not submit twice.

I am getting following error in console log, when I accidentally clicked two times.

```
Uncaught (in promise) DOMException: The operation was aborted. 
```

**Comment by tonysm** [comment]
Turbo dispatches events on form submissions. You can read more about that [here](https://turbo.hotwire.dev/reference/events).

So, you can listen to those events on your form and toggle buttons on and off as you wish. Here's an example using Alpine.js:

```blade
<form
  x-data="{ sending: false }"
  @turbo:submit-start="sending = true"
  @turbo:submit-end="sending = false"
>
  <!-- more fields here... -->

  <button x-bind:disable="sending" type="submit">
    <span x-show="sending">Saving...</span>
    <span x-show="!sending">Save</span>
  </button>
</form>
```

I've added that example to the demo app, see [here](https://github.com/tonysm/turbo-demo-app/commit/92ec8a147a3e463d8cde28a60e8aebc02deb4a0a).
