### ISSUE TITLE
`turbo_stream()` helper

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#91]
https://github.com/johnnyfreeman/laravel-turbo

I think having `turbo_stream()` is a good idea :)

**Comment by tonysm** [comment]
Yeah, I've been thinking about that. I'm getting a bit tired of doing things like `response()->turboStream()->...` maybe having a global `turbo_stream()` function is the way to go. I also like it that the one you mentioned implements the `HtmlString` so it can be used inside blade components as well. I don't know about being able to chain them, though. I'll see what I can do.

**Comment by bilogic** [comment]
Yup, melting pot of ideas!
