### ISSUE TITLE
[Question] How does turbo-frame work with a livewire component :question: 

### ISSUE THREAD

**Issue by mccarlosen** [tonysm/turbo-laravel#93]
:question: 
Hello, how does turbo-frame work with a livewire component? Is it possible?

**Comment by tonysm** [comment]
@mccarlosen it depends on what you expect will happen. The livewire component can live inside a Turbo Frame. The LW component has its own rendering cycle, though. So, it will render independently of the frame. Whenever the frame itself rerenders, the LW component will likely be reinitiated. I do have an example in the [demo app](https://github.com/tonysm/turbo-demo-app/blob/main/resources/views/livewire-integration.blade.php#L31-L33).

What are you expecting to happen?

**Comment by tonysm** [comment]
Closing, as there doesn't seem to be an issue between Livewire and Turbo. Feel free to reply or re-open if you think something is not working properly.
